import { Router } from "express";
import { supabaseAdmin } from "../supabase.js";
import { getConfig } from "../services/config.js";
import { sendOrderConfirmationEmail } from "../services/email.js";

const router = Router();

// Helper for Fapshi Requests
async function getFapshiConfig() {
  const config = getConfig();
  const fapshiInt = config.integrations.find((i: any) => i.id === 'fapshi');
  if (!fapshiInt || !fapshiInt.isActive) {
    throw new Error('Fapshi integration is disabled or not configured');
  }
  return fapshiInt.config;
}

async function fapshiRequest(endpoint: string, data: any) {
  const fapshiConfig = await getFapshiConfig();
  const response = await fetch(`${fapshiConfig.baseUrl}${endpoint}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apiuser": fapshiConfig.apiUser,
      "apikey": fapshiConfig.apiKey,
    },
    body: JSON.stringify(data),
  });
  return response.json();
}

async function fapshiGet(endpoint: string) {
  const fapshiConfig = await getFapshiConfig();
  const response = await fetch(`${fapshiConfig.baseUrl}${endpoint}`, {
    headers: {
      "apiuser": fapshiConfig.apiUser,
      "apikey": fapshiConfig.apiKey,
    },
  });
  return response.json();
}


router.post("/checkout", async (req, res) => {
  if (!supabaseAdmin) return res.status(500).json({ error: "Supabase not configured" });
  
  const { userId, sellerId, amount, items } = req.body;
  if (!userId || !sellerId || !amount) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  try {
    // 1. Get commission
    const config = getConfig();
    const commPercent = config.commission_percentage || 5.0;
    
    const commission_amount = amount * (commPercent / 100);
    const seller_earnings = amount - commission_amount;

    // 2. Create pending order
    // Assuming `id` is a UUID generated by DB or we can pass one. Wait, in Supabase typically we let it generate UUID or we use one. Let's let it generate.
    const { data: order, error: orderErr } = await supabaseAdmin.from('orders').insert({
      buyer_id: userId, // Assuming columns match standard
      seller_id: sellerId,
      total: amount,
      items: items || [],
      status: 'pending',
      payment_status: 'pending',
      commission_amount,
      seller_earnings,
      created_at: new Date().toISOString()
    }).select().single();

    if (orderErr) throw orderErr;

    // 3. Initiate Fapshi Pay
    const fapshiRes = await fapshiRequest("/initiate-pay", {
      amount: Math.round(amount),
      email: "buyer@example.com", // In a real app we'd get from user profile
      userId: userId,
      externalId: order.id,
      redirectUrl: `${req.headers.origin || 'http://localhost:3000'}/buyer/orders/${order.id}`
    });

    if (fapshiRes.statusCode !== 200) {
      throw new Error(fapshiRes.message || "Failed to initiate payment");
    }

    // Update order with trans_id
    await supabaseAdmin.from('orders').update({ fapshi_trans_id: fapshiRes.transId }).eq('id', order.id);

    res.json({ link: fapshiRes.link, orderId: order.id });
  } catch (err: any) {
    console.error("Checkout error:", err);
    res.status(500).json({ error: err.message });
  }
});

router.post("/webhook", async (req, res) => {
  if (!supabaseAdmin) return res.status(500).json({ error: "Supabase not configured" });
  
  // Verify webhook signature if Fapshi provides one (skipping for sandbox)
  const { transId, status, externalId } = req.body;
  
  if (status === 'SUCCESSFUL') {
    try {
      // Find order
      const { data: order } = await supabaseAdmin.from('orders').select('*').eq('id', externalId).single();
      
      if (order && order.payment_status !== 'paid') {
        // Update order
        await supabaseAdmin.from('orders').update({ payment_status: 'paid', status: 'processing' }).eq('id', externalId);
        
        // Send order confirmation email
        const { data: buyer } = await supabaseAdmin.from('profiles').select('email, first_name').eq('id', order.buyer_id).single();
        if (buyer && buyer.email) {
          await sendOrderConfirmationEmail(buyer.email, buyer.first_name, order);
        }
        
        // In a complete implementation, credit seller wallet here if using a wallet table
        // Example: await supabaseAdmin.rpc('increment_seller_wallet', { seller: order.seller_id, amount: order.seller_earnings })
      }
    } catch(err) {
      console.error("Webhook processing error:", err);
    }
  }

  res.json({ received: true });
});

router.get("/status/:transId", async (req, res) => {
  try {
    const { transId } = req.params;
    const statusRes = await fapshiGet(`/payment-status/${transId}`);
    res.json(statusRes);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Admin payout route
router.post("/payout", async (req, res) => {
  // Normally add requireAdmin middleware here, keeping simple for this file if not attached globally
  const { amount, phone, name } = req.body;
  try {
    const payoutRes = await fapshiRequest("/payout", {
      amount: Math.round(amount),
      phone, // Mobile money number
      name
    });
    res.json(payoutRes);
  } catch(err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
